language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
cache:
  yarn: true
  directories:
  - node_modules
  - "$HOME/.rvm"
before_install:
  - rvm install 2.2.5
  - rvm use 2.2.5
script:
  - yarn global add coveralls
  - gem install fastlane
  - yarn test
  - yarn coverage
sudo: false
