# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.96.0"

setup_travis

default_platform :ios

SLACK_POST = true
if ENV['SLACK_ROOM'].nil? or ENV['SLACK_ROOM'].empty?
  SLACK_POST = false
end
if ENV['SLACK_URL'].nil? or ENV['SLACK_URL'].empty?
  SLACK_POST = false
end

platform :ios do

  private_lane :build_app_production do
    sigh(
      app_identifier: ENV['APP_IDENTIFIER'],
      username: ENV['APPLE_ID']
    )

    update_project_provisioning(
      xcodeproj: "#{ENV['METEOR_OUTPUT_ABSOLUTE']}/ios/project/#{ENV['XCODE_SCHEME_NAME']}.xcodeproj",
      profile: lane_context[SharedValues::SIGH_PROFILE_PATH],
      target_filter: ENV['XCODE_SCHEME_NAME'],
      build_configuration: "Release"
    )

    update_project_team(
      path: "#{ENV['METEOR_OUTPUT_ABSOLUTE']}/ios/project/#{ENV['XCODE_SCHEME_NAME']}.xcodeproj",
      teamid: "8M3X28P97Q"
    )

    gym(
      scheme: ENV['XCODE_SCHEME_NAME'],
      project: "#{ENV['METEOR_OUTPUT_ABSOLUTE']}/ios/project/#{ENV['XCODE_SCHEME_NAME']}.xcodeproj",
      include_bitcode: false,
      export_method: "app-store",
      export_team_id: "8M3X28P97Q"
    )
  end

  private_lane :build_app_ad_hoc do
    sigh(
      app_identifier: ENV['APP_IDENTIFIER'],
      username: ENV['APPLE_ID'],
      adhoc: true,
      skip_certificate_verification: true
    )

    update_project_provisioning(
      xcodeproj: "#{ENV['METEOR_OUTPUT_ABSOLUTE']}/ios/project/#{ENV['XCODE_SCHEME_NAME']}.xcodeproj",
      profile: lane_context[SharedValues::SIGH_PROFILE_PATH],
      target_filter: ENV['XCODE_SCHEME_NAME'],
      build_configuration: "Release"
    )

    update_project_team(
      path: "#{ENV['METEOR_OUTPUT_ABSOLUTE']}/ios/project/#{ENV['XCODE_SCHEME_NAME']}.xcodeproj",
      teamid: "8M3X28P97Q"
    )

    gym(
      use_legacy_build_api: true,
      scheme: ENV['XCODE_SCHEME_NAME'],
      project: "#{ENV['METEOR_OUTPUT_ABSOLUTE']}/ios/project/#{ENV['XCODE_SCHEME_NAME']}.xcodeproj",
      include_bitcode: false,
      export_method: "ad-hoc",
      export_team_id: "8M3X28P97Q"
    )
  end

  desc "Just build the app"
  lane :build do
    build_app_production
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    import_certificates

    build_app_production

    pilot(
      username: ENV['APPLE_ID'],
      skip_waiting_for_build_processing: true
    )
  end

  desc "Submit a new Beta Build to Hockey"
  desc "This will also make sure the profile is up to date"
  lane :hockey do
    import_certificates

    build_app_ad_hoc

    hockey(
      api_token: ENV['IOS_HOCKEY_TOKEN'],
      notify: "0",
      status: "1"
    )
  end

  desc "Deploy a new version to the App Store"
  desc "** Full Markdown** Support: `code`"
  lane :deploy do
    build_app_production

    deliver(
      username: ENV['APPLE_ID'],
      force: true
    )
  end

  after_all do |lane|
    if SLACK_POST
      slack(
        message: "App successfully released through: #{lane}",
        channel: ENV['SLACK_ROOM'],
        slack_url: ENV['SLACK_URL']
      )
    end
  end

  error do |lane, exception|
    if SLACK_POST
      slack(
        message: "Lane #{lane} failed! #{exception}",
        channel: ENV['SLACK_ROOM'],
        slack_url: ENV['SLACK_URL'],
        success: false
      )
    end
  end

  def import_certificates
    match(
      git_url: "https://github.com/moisaconsulting/apple-certs",
      app_identifier: "com.ticketnetworkmobile.pos2",
      username: "amoisa@me.com",
      readonly: true,
      type: "development"
    )

    match(
      git_url: "https://github.com/moisaconsulting/apple-certs",
      app_identifier: "com.ticketnetworkmobile.pos2",
      username: "amoisa@me.com",
      readonly: true,
      type: "adhoc"
    )

    match(
      git_url: "https://github.com/moisaconsulting/apple-certs",
      app_identifier: "com.ticketnetworkmobile.pos2",
      username: "amoisa@me.com",
      readonly: true,
      type: "appstore"
    )
  end
end


# More information about multiple platforms in fastlane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
